name: CustomRecipes
version: '1.5.0'
main: org.hikarii.customrecipes.CustomRecipes
api-version: '1.21'
author: hikarii
description: Create your own custom Crafting, Furnace, Anvil, and other recipes with tons of configuration option
website:
  https://discord.gg/ChTjgTqw3T
  https://modrinth.com/user/hikarii-dev
  https://www.spigotmc.org/members/hikarii.2411622/
  https://hangar.papermc.io/hikarii/Custom-Recipes
  https://github.com/hikarii-dev

commands:
  customrecipes:
    description: Main CustomRecipes command
    usage: /customrecipes <list|help|reload|gui>
    aliases: [cr, crecipes, customrecipe]

permissions:
  customrecipes.*:
    description: Grants all CustomRecipes permissions
    default: op
    children:
      customrecipes.reload: true
      customrecipes.gui: true
      customrecipes.manage: true
      customrecipes.list: true
      customrecipes.update.notify: true

  customrecipes.reload:
    description: Allows reloading the plugin configuration
    default: op

  customrecipes.gui:
    description: Allows opening the recipe management GUI (admin only)
    default: op

  customrecipes.manage:
    description: Allows enabling, disabling, and deleting recipes
    default: op

  customrecipes.list:
    description: Allows viewing all custom recipes
    default: true

  customrecipes.update.notify:
    description: Receive update notifications on join
    default: op